name = "hono-js"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

# Binding Database D1 SQLite 
[[d1_databases]]
binding = "beda_pos"
database_name = "beda_pos"
database_id = "9acf87ab-5048-43fd-90fc-88862e0b6b7f"

# Bindings R2 Bucket (sesuai nama bucket di Cloudflare R2 Anda)
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "beda-asset"

# Environment Variables
[vars]
MYSQLPORT = "3306"
R2_BUCKET_STR = "beda-asset"